### ISSUE TITLE
MicroLens-100k_likes_and_views.txt数据问题

### ISSUE THREAD

**Issue by Gargantua43** [westlake-repl/MicroLens#10]
作者您好，这是MicroLens-100k_likes_and_views.txt文件的部分截图；请问作者第二列数据是表示点赞数嚒？第三例表示浏览数嚒？十分感谢您的回复
![图片](https://github.com/user-attachments/assets/a4bd3f89-ac3e-4da1-9cb9-da047e429334)

**Comment by yxni98** [comment]
@Gargantua43 是的。

**Comment by Gargantua43** [comment]
@yxni98 请问为什么会出现Likes大于Views的情况呢？十分感谢您的回复
![图片](https://github.com/user-attachments/assets/a62e6500-04da-4815-a0f7-61d51c37ce0e)

**Comment by Gargantua43** [comment]
> @Gargantua43 你好 我们如实记录了点赞数和浏览量 以上这种情况是比较少见的 不排除有人专门用脚本给视频刷赞以获得高流量的可能。这类属于异常数据且占极少数 如果您要做点赞和浏览量相关的研究 建议您预处理去掉这种不合理数据。

十分感谢您的回复！我已删除出现问题的样本
