### ISSUE TITLE
502 Bad Gateway when downloading datasets (both 100k and 50k)

### ISSUE THREAD

**Issue by ZzMeei** [westlake-repl/MicroLens#11]
Hi,

Thanks for your valuable open-source datasets and good work. I found that there might some error when downloading datasets (both 100k and 50k) ? It shows "502 Bad Gateway".

**Comment by yxni98** [comment]
@ZzMeei Thanks for reminding me, I am communicating with the service provider, and I will reply again when it's fixed.

**Comment by yxni98** [comment]
@ZzMeei fixed.
