### ISSUE TITLE
Raw data disclosure

### ISSUE THREAD

**Issue by fightingman1** [westlake-repl/MicroLens#12]
I found that in the data set, the source of many videos should be in Chinese video websites, so the original data should be in Chinese. Your use of translation to translate the data set into English has caused some semantic errors. 
For example, in 10145.mp4, the original title should be ”带土和琳“(Two anime character names), but the translation becomes "Take dirt and Lin". 
Therefore, in order to avoid this problem, it is hoped that the author can disclose the source of the original data.

**Comment by yxni98** [comment]
Hi @fightingman1 , we cannot disclose it publicly at the moment due to the purpose of protecting privacy and copyright. If you require, please contact the corresponding author and cc me. I will send it to you via email upon obtaining approval from the project leader.

**Comment by fightingman1** [comment]
Thank you for your reply, maybe I didn't express myself clearly enough and caused your misunderstanding. I am not asking to disclose all the original data, but I want MicroLens-50k_titles.csv / MicroLens-100k_titles.csv untranslated data. Because the contents of the titles column in these two csvs are translated and the translated contents have some differences from the original semantics, which is not favourable to the performance of the MicroLens dataset on some tasks. And there are no privacy and copyright issues involved in making the untranslated MicroLens-50k_titles.csv / MicroLens-100k_titles.csv files public, so we hope that the authors can make this part of the data public.

**Comment by yxni98** [comment]
Hi @fightingman1 , the original caption could help trace the original video, and the inter-behavior of users among videos would expose their real identity, that's why they are translated. We have prepared and are happy to share the original text data. Please contact us through the email in the way I suggested before, and I will send you the data immediately upon obtaining approval from the project leader.

**Comment by fightingman1** [comment]
Okay, thanks for your reply.
