### ISSUE TITLE
关于实验结果以及权重参数的问题

### ISSUE THREAD

**Issue by DaiMaocai** [westlake-repl/MicroLens#16]
作者您好，我在根据提示实现本篇论文的实验（NextItNet_v、GRU4Rec_v、SASRec_v）的时候，在测试阶段出现了两个问题：

1. 第1个是实验结果不太匹配：
- 首先这是您文章当中的结果
![paper_results](https://github.com/user-attachments/assets/595b109c-9e88-4aee-9218-350ed9273529)
- 这个是SASRec_v最后的训练结果，我测试取的权重就是最高的这一个（epoch-46.pt）
 ![SASRec_train](https://github.com/user-attachments/assets/fbbf0836-0c74-42e4-b5d4-ab7e993f3ec1)
然后这是根据这个权重测试得到的结果
![SASRec_test](https://github.com/user-attachments/assets/01845e01-1af7-46fd-9354-e33014670bed)
但是和您文章当中的结果存在出入
- 同样在NextItNet_v的测试当中也同样有这个问题，取得权重epoch-29.pt
![NextItNet](https://github.com/user-attachments/assets/4939d445-5a9d-4d35-90d9-372a4db4ab51)
然后这是测试结果
![NextItNet_test](https://github.com/user-attachments/assets/8f9db79b-9831-4f3b-9fe1-7f9e53804b06)
也是和您文章当中的结果存在出入，能否给予一下解答或者帮助呢？
2. 第2个问题是对于GRU4Rec_v模型在测试的时候出现了关于权重参数不匹配的报错
在训练得到各个epoch的权重之后，选择了最高的一个进行测试，但是就出现了如下报错：
![image](https://github.com/user-attachments/assets/ce7aa43a-941b-436d-bc46-6d6a5775da06)
所以想请问一下这个问题是怎么回事呢，同样能请您给予一下解答或则帮助吗？（因为在对另外两个模型进行测试时没有出现报错，所以我有点不知道是哪里出了问题）

谢谢！

**Comment by DaiMaocai** [comment]
不好意思作者，第二个问题关于GRU4Rec_v模型的解决了，测试的时候block_num这个参数没有传进入，训练的时候是1，但是测试的时候没传默认为2了
但是测试结果还是和您文章当中的结果存在较大差异（GRU4Rec_v）
![GRU4Rec_test](https://github.com/user-attachments/assets/20b0773e-b1c7-4a17-ace3-f090d4bd7ba7)

**Comment by DaiMaocai** [comment]
@yxni98 麻烦看到了有时间的话解答一下，十分感谢，要是这里不方便的话，这是我的邮箱dahat123@163.com，十分感谢十分感谢！！

**Comment by DaiMaocai** [comment]
作者您好，请问是一定要分到四张卡上面训练才可以吗，我是把batchsize改小了然后在一张卡上面跑到，其他参数都是您开源代码当中设置的，基本上没有变



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yxni98 ***@***.***&gt;
发送时间: 2024年12月1日 18:37
收件人: westlake-repl/MicroLens ***@***.***&gt;
抄送: 戴茂才 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [westlake-repl/MicroLens] 关于实验结果以及权重参数的问题 (Issue #16)

**Comment by yxni98** [comment]
@DaiMaocai 单卡和多卡设置自然会带来不一样的结果，我在实验过程中batchsize是一个非常重要的参数。由于video encoder彼此之间非常不一样，所以batchsize是需要搜索的，我写在代码里的batchsize对应了论文结果的复现。

**Comment by DaiMaocai** [comment]
好嘞，谢谢您，我重新试试看🌹🌹



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yxni98 ***@***.***&gt;
发送时间: 2024年12月1日 20:01
收件人: westlake-repl/MicroLens ***@***.***&gt;
抄送: 戴茂才 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [westlake-repl/MicroLens] 关于实验结果以及权重参数的问题 (Issue #16)
