### ISSUE TITLE
preprocessing

### ISSUE THREAD

**Issue by Panamera2333** [westlake-repl/MicroLens#4]
Hi,Thanks to your excellent work!I would like to know how you processed the raw image and text modes to get the.npy file. Can you share the code for the process?

**Comment by microlens2023** [comment]
Hi @Panamera2333 , sorry for delayed response.

The feature extraction code can be seen from https://github.com/westlake-repl/MicroLens/blob/master/Data%20Processing/video_feature_extraction_(from_lmdb).py
