### ISSUE TITLE
Where is the likes and views of the videos?

### ISSUE THREAD

**Issue by DOGGOD11** [westlake-repl/MicroLens#5]
I see that in the preview the likes and views is shown but in the dataset I failed to find them, so I wonder where can I acquire them?

**Comment by yxni98** [comment]
Hi @DOGGOD11 , thanks for your reminder, I have uploaded the corresponding files to the directory, please see the "likes_and_views.txt" in the folders.

**Comment by DOGGOD11** [comment]
Thank you very much!
