### ISSUE TITLE
video_frame_100k.lmdb

### ISSUE THREAD

**Issue by Gargantua43** [westlake-repl/MicroLens#7]
Thank you very much for your work, but while reading "video_feature_extraction_(from_lmdb).py" I realized that I didn't find "video_frames_100k.lmdb". " file. I also downloaded the MicroLens-100k dataset and did not find the above ".lmdb" file in that dataset either. I hope you can give me the corresponding download address or file storage path.
![图片](https://github.com/westlake-repl/MicroLens/assets/100502303/d29aa004-860e-42b1-bc67-523c016e7876)

**Comment by yxni98** [comment]
Hi @Gargantua43 , the lmdb data is generated via the provided code [generate_cover_frames_lmdb.py](https://github.com/westlake-repl/MicroLens/blob/master/Data%20Processing/generate_cover_frames_lmdb.py), please see the scripts in the same directory.
