### ISSUE TITLE
run_video.py

### ISSUE THREAD

**Issue by Gargantua43** [westlake-repl/MicroLens#9]
Running run_video.py produced the problem shown below:
![图片](https://github.com/westlake-repl/MicroLens/assets/100502303/ec17e6ff-8ef4-4b49-8d25-dd4c965acfa1)
However, I tried modifying the code in x3d.py at lines 541 512 and 715-719; the following figure shows the result of the modification at line 541 and the result of the modification at lines 712-719. However, it is not clear how to modify line 512, and I would also like the author to give me the specific modification. Thank you very much for your reply!
![图片](https://github.com/westlake-repl/MicroLens/assets/100502303/a01eb268-ed7b-49d9-9355-9c67de1ec30c)
![图片](https://github.com/westlake-repl/MicroLens/assets/100502303/5e01bb44-385b-4370-be31-8335d96077ee)
![图片](https://github.com/westlake-repl/MicroLens/assets/100502303/1b71510d-a566-4004-b6ff-5c90619e65ff)

**Comment by yxni98** [comment]
The same issue has been addressed, please see my response to you under another issue.
